<#
.SYNOPSIS
  Compare two Windows inventory snapshots to detect changes (CCDC Edition).

.DESCRIPTION
  Compares two inventory folders generated by Get-WindowsInventory.ps1 and identifies:
    - New/removed processes, services, scheduled tasks
    - New/removed users and group members
    - New/removed software packages
    - New/removed network connections
    - New/removed autoruns
    - Changes to firewall rules
    - Modified files in critical directories

  Generates a diff report highlighting suspicious changes for CCDC defenders.

.PARAMETER BaselinePath
  Path to the baseline inventory folder (first/older snapshot).

.PARAMETER CurrentPath
  Path to the current inventory folder (second/newer snapshot).

.PARAMETER OutputPath
  Path for diff report output. Default: current directory.

.PARAMETER ShowUnchanged
  Include unchanged items in the report (verbose mode).

.EXAMPLE
  .\Compare-WindowsInventory.ps1 -BaselinePath .\Inventory_SERVER_20250115_100000 -CurrentPath .\Inventory_SERVER_20250115_110000

.EXAMPLE
  .\Compare-WindowsInventory.ps1 -BaselinePath C:\CCDC\Baseline\Inventory_* -CurrentPath .\Inventory_*

.NOTES
  CCDC Optimized: Highlights suspicious changes in red for quick triage.
  Version: 1.0
#>

[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)]
  [string]$BaselinePath,

  [Parameter(Mandatory=$true)]
  [string]$CurrentPath,

  [string]$OutputPath = (Get-Location).Path,

  [switch]$ShowUnchanged
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

# Helper function to compare CSV files
function Compare-CsvData {
  param(
    [string]$BaselineCsv,
    [string]$CurrentCsv,
    [string[]]$KeyProperties
  )

  if (-not (Test-Path $BaselineCsv) -or -not (Test-Path $CurrentCsv)) {
    return $null
  }

  try {
    $baseline = Import-Csv $BaselineCsv -ErrorAction Stop
    $current = Import-Csv $CurrentCsv -ErrorAction Stop

    # Create comparison key
    $baselineKeys = @{}
    $currentKeys = @{}

    foreach ($item in $baseline) {
      $key = ($KeyProperties | ForEach-Object { $item.$_ }) -join '|'
      if ($key) { $baselineKeys[$key] = $item }
    }

    foreach ($item in $current) {
      $key = ($KeyProperties | ForEach-Object { $item.$_ }) -join '|'
      if ($key) { $currentKeys[$key] = $item }
    }

    # Find additions and removals
    $added = @()
    $removed = @()

    foreach ($key in $currentKeys.Keys) {
      if (-not $baselineKeys.ContainsKey($key)) {
        $added += $currentKeys[$key]
      }
    }

    foreach ($key in $baselineKeys.Keys) {
      if (-not $currentKeys.ContainsKey($key)) {
        $removed += $baselineKeys[$key]
      }
    }

    return [pscustomobject]@{
      Added = $added
      Removed = $removed
      BaselineCount = $baseline.Count
      CurrentCount = $current.Count
    }
  } catch {
    Write-Warning "Failed to compare $BaselineCsv and $CurrentCsv: $_"
    return $null
  }
}

# Function to assess suspicion level
function Get-SuspicionLevel {
  param(
    [string]$Category,
    [object]$Item
  )

  switch ($Category) {
    "Process" {
      if ($Item.Path -match '(temp|appdata\\local\\temp|public)') { return "High" }
      if ($Item.Name -match '^(cmd|powershell|pwsh|wscript|cscript)$') { return "Medium" }
      return "Low"
    }
    "Service" {
      if ($Item.PathName -match '(temp|appdata|public)' -and $Item.StartMode -eq 'Auto') { return "High" }
      if ($Item.StartName -eq 'LocalSystem' -and $Item.PathName -match 'users') { return "High" }
      return "Low"
    }
    "ScheduledTask" {
      if ($Item.Actions -match '(temp|appdata)') { return "High" }
      if ($Item.Actions -match 'powershell.*(-enc|-w hidden)') { return "High" }
      return "Low"
    }
    "User" {
      return "Medium"
    }
    "Admin" {
      return "High"
    }
    "Autorun" {
      if ($Item.Location -match '(Run|Startup)') { return "Medium" }
      return "Low"
    }
    "NetworkConnection" {
      if ($Item.RemotePort -in @(4444, 5555, 6666, 7777, 8888, 31337, 1337)) { return "High" }
      return "Low"
    }
    default {
      return "Low"
    }
  }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Windows Inventory Diff - CCDC Edition" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Resolve paths (handle wildcards)
$baselineDir = Get-Item $BaselinePath -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
$currentDir = Get-Item $CurrentPath -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName

if (-not $baselineDir -or -not (Test-Path $baselineDir)) {
  Write-Error "Baseline path not found: $BaselinePath"
  exit 1
}

if (-not $currentDir -or -not (Test-Path $currentDir)) {
  Write-Error "Current path not found: $CurrentPath"
  exit 1
}

Write-Host "Baseline: $baselineDir" -ForegroundColor Yellow
Write-Host "Current:  $currentDir" -ForegroundColor Yellow
Write-Host ""

# Create output folder
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$diffDir = Join-Path $OutputPath "InventoryDiff_$timestamp"
New-Item -ItemType Directory -Path $diffDir -Force | Out-Null
$csvDir = Join-Path $diffDir "csv"
New-Item -ItemType Directory -Path $csvDir -Force | Out-Null

Write-Host "Comparing inventories..." -ForegroundColor Cyan

# Initialize diff report
$diffReport = [ordered]@{
  Metadata = [ordered]@{
    BaselinePath = $baselineDir
    CurrentPath = $currentDir
    ComparisonTime = (Get-Date).ToString("o")
    BaselineName = Split-Path $baselineDir -Leaf
    CurrentName = Split-Path $currentDir -Leaf
  }
  Processes = $null
  Services = $null
  ScheduledTasks = $null
  Users = $null
  GroupMembers = $null
  Software = $null
  Autoruns = $null
  EstablishedConnections = $null
  Patches = $null
  Shares = $null
  SuspiciousChanges = @()
}

# Compare Processes
Write-Host "  [+] Comparing processes..." -ForegroundColor Gray
$procDiff = Compare-CsvData `
  -BaselineCsv (Join-Path $baselineDir "csv\processes.csv") `
  -CurrentCsv (Join-Path $currentDir "csv\processes.csv") `
  -KeyProperties @("Name", "Id")

if ($procDiff) {
  $diffReport.Processes = [pscustomobject]@{
    Added = $procDiff.Added.Count
    Removed = $procDiff.Removed.Count
    BaselineTotal = $procDiff.BaselineCount
    CurrentTotal = $procDiff.CurrentCount
  }

  if ($procDiff.Added.Count -gt 0) {
    $procDiff.Added | Export-Csv (Join-Path $csvDir "diff_processes_added.csv") -NoTypeInformation

    # Check for suspicious new processes
    foreach ($proc in $procDiff.Added) {
      $suspicion = Get-SuspicionLevel -Category "Process" -Item $proc
      if ($suspicion -in @("High", "Medium")) {
        $diffReport.SuspiciousChanges += [pscustomobject]@{
          Category = "Process"
          Change = "Added"
          Item = "$($proc.Name) (PID: $($proc.Id))"
          Details = "Path: $($proc.Path)"
          SuspicionLevel = $suspicion
        }
      }
    }
  }

  if ($procDiff.Removed.Count -gt 0) {
    $procDiff.Removed | Export-Csv (Join-Path $csvDir "diff_processes_removed.csv") -NoTypeInformation
  }
}

# Compare Services
Write-Host "  [+] Comparing services..." -ForegroundColor Gray
$svcDiff = Compare-CsvData `
  -BaselineCsv (Join-Path $baselineDir "csv\services.csv") `
  -CurrentCsv (Join-Path $currentDir "csv\services.csv") `
  -KeyProperties @("Name")

if ($svcDiff) {
  $diffReport.Services = [pscustomobject]@{
    Added = $svcDiff.Added.Count
    Removed = $svcDiff.Removed.Count
    BaselineTotal = $svcDiff.BaselineCount
    CurrentTotal = $svcDiff.CurrentCount
  }

  if ($svcDiff.Added.Count -gt 0) {
    $svcDiff.Added | Export-Csv (Join-Path $csvDir "diff_services_added.csv") -NoTypeInformation

    foreach ($svc in $svcDiff.Added) {
      $suspicion = Get-SuspicionLevel -Category "Service" -Item $svc
      if ($suspicion -in @("High", "Medium")) {
        $diffReport.SuspiciousChanges += [pscustomobject]@{
          Category = "Service"
          Change = "Added"
          Item = "$($svc.DisplayName) ($($svc.Name))"
          Details = "Path: $($svc.PathName), StartMode: $($svc.StartMode)"
          SuspicionLevel = $suspicion
        }
      }
    }
  }

  if ($svcDiff.Removed.Count -gt 0) {
    $svcDiff.Removed | Export-Csv (Join-Path $csvDir "diff_services_removed.csv") -NoTypeInformation
  }
}

# Compare Scheduled Tasks
Write-Host "  [+] Comparing scheduled tasks..." -ForegroundColor Gray
$taskDiff = Compare-CsvData `
  -BaselineCsv (Join-Path $baselineDir "csv\scheduled_tasks.csv") `
  -CurrentCsv (Join-Path $currentDir "csv\scheduled_tasks.csv") `
  -KeyProperties @("TaskName", "TaskPath")

if ($taskDiff) {
  $diffReport.ScheduledTasks = [pscustomobject]@{
    Added = $taskDiff.Added.Count
    Removed = $taskDiff.Removed.Count
    BaselineTotal = $taskDiff.BaselineCount
    CurrentTotal = $taskDiff.CurrentCount
  }

  if ($taskDiff.Added.Count -gt 0) {
    $taskDiff.Added | Export-Csv (Join-Path $csvDir "diff_scheduled_tasks_added.csv") -NoTypeInformation

    foreach ($task in $taskDiff.Added) {
      $suspicion = Get-SuspicionLevel -Category "ScheduledTask" -Item $task
      if ($suspicion -in @("High", "Medium")) {
        $diffReport.SuspiciousChanges += [pscustomobject]@{
          Category = "ScheduledTask"
          Change = "Added"
          Item = "$($task.TaskName)"
          Details = "Path: $($task.TaskPath), Actions: $($task.Actions)"
          SuspicionLevel = $suspicion
        }
      }
    }
  }

  if ($taskDiff.Removed.Count -gt 0) {
    $taskDiff.Removed | Export-Csv (Join-Path $csvDir "diff_scheduled_tasks_removed.csv") -NoTypeInformation
  }
}

# Compare Local Users
Write-Host "  [+] Comparing local users..." -ForegroundColor Gray
$userDiff = Compare-CsvData `
  -BaselineCsv (Join-Path $baselineDir "csv\local_users.csv") `
  -CurrentCsv (Join-Path $currentDir "csv\local_users.csv") `
  -KeyProperties @("Name")

if ($userDiff) {
  $diffReport.Users = [pscustomobject]@{
    Added = $userDiff.Added.Count
    Removed = $userDiff.Removed.Count
    BaselineTotal = $userDiff.BaselineCount
    CurrentTotal = $userDiff.CurrentCount
  }

  if ($userDiff.Added.Count -gt 0) {
    $userDiff.Added | Export-Csv (Join-Path $csvDir "diff_users_added.csv") -NoTypeInformation

    foreach ($user in $userDiff.Added) {
      $diffReport.SuspiciousChanges += [pscustomobject]@{
        Category = "User"
        Change = "Added"
        Item = $user.Name
        Details = "Enabled: $($user.Enabled), Description: $($user.Description)"
        SuspicionLevel = "Medium"
      }
    }
  }

  if ($userDiff.Removed.Count -gt 0) {
    $userDiff.Removed | Export-Csv (Join-Path $csvDir "diff_users_removed.csv") -NoTypeInformation
  }
}

# Compare Group Members (especially Administrators)
Write-Host "  [+] Comparing group memberships..." -ForegroundColor Gray
$memberDiff = Compare-CsvData `
  -BaselineCsv (Join-Path $baselineDir "csv\local_group_members.csv") `
  -CurrentCsv (Join-Path $currentDir "csv\local_group_members.csv") `
  -KeyProperties @("Group", "Member")

if ($memberDiff) {
  $diffReport.GroupMembers = [pscustomobject]@{
    Added = $memberDiff.Added.Count
    Removed = $memberDiff.Removed.Count
    BaselineTotal = $memberDiff.BaselineCount
    CurrentTotal = $memberDiff.CurrentCount
  }

  if ($memberDiff.Added.Count -gt 0) {
    $memberDiff.Added | Export-Csv (Join-Path $csvDir "diff_group_members_added.csv") -NoTypeInformation

    foreach ($member in $memberDiff.Added) {
      $suspicion = if ($member.Group -match 'Administrators') { "High" } else { "Low" }
      if ($suspicion -eq "High") {
        $diffReport.SuspiciousChanges += [pscustomobject]@{
          Category = "GroupMember"
          Change = "Added"
          Item = "$($member.Member) → $($member.Group)"
          Details = "ObjectClass: $($member.ObjectClass)"
          SuspicionLevel = $suspicion
        }
      }
    }
  }

  if ($memberDiff.Removed.Count -gt 0) {
    $memberDiff.Removed | Export-Csv (Join-Path $csvDir "diff_group_members_removed.csv") -NoTypeInformation
  }
}

# Compare Installed Software
Write-Host "  [+] Comparing installed software..." -ForegroundColor Gray
$softwareDiff = Compare-CsvData `
  -BaselineCsv (Join-Path $baselineDir "csv\installed_software_registry.csv") `
  -CurrentCsv (Join-Path $currentDir "csv\installed_software_registry.csv") `
  -KeyProperties @("DisplayName", "DisplayVersion")

if ($softwareDiff) {
  $diffReport.Software = [pscustomobject]@{
    Added = $softwareDiff.Added.Count
    Removed = $softwareDiff.Removed.Count
    BaselineTotal = $softwareDiff.BaselineCount
    CurrentTotal = $softwareDiff.CurrentCount
  }

  if ($softwareDiff.Added.Count -gt 0) {
    $softwareDiff.Added | Export-Csv (Join-Path $csvDir "diff_software_added.csv") -NoTypeInformation
  }

  if ($softwareDiff.Removed.Count -gt 0) {
    $softwareDiff.Removed | Export-Csv (Join-Path $csvDir "diff_software_removed.csv") -NoTypeInformation
  }
}

# Compare Autoruns
Write-Host "  [+] Comparing autoruns..." -ForegroundColor Gray
$autorunDiff = Compare-CsvData `
  -BaselineCsv (Join-Path $baselineDir "csv\autoruns.csv") `
  -CurrentCsv (Join-Path $currentDir "csv\autoruns.csv") `
  -KeyProperties @("Location", "Name")

if ($autorunDiff) {
  $diffReport.Autoruns = [pscustomobject]@{
    Added = $autorunDiff.Added.Count
    Removed = $autorunDiff.Removed.Count
    BaselineTotal = $autorunDiff.BaselineCount
    CurrentTotal = $autorunDiff.CurrentCount
  }

  if ($autorunDiff.Added.Count -gt 0) {
    $autorunDiff.Added | Export-Csv (Join-Path $csvDir "diff_autoruns_added.csv") -NoTypeInformation

    foreach ($autorun in $autorunDiff.Added) {
      $suspicion = Get-SuspicionLevel -Category "Autorun" -Item $autorun
      if ($suspicion -in @("High", "Medium")) {
        $diffReport.SuspiciousChanges += [pscustomobject]@{
          Category = "Autorun"
          Change = "Added"
          Item = $autorun.Name
          Details = "Location: $($autorun.Location), Value: $($autorun.Value)"
          SuspicionLevel = $suspicion
        }
      }
    }
  }

  if ($autorunDiff.Removed.Count -gt 0) {
    $autorunDiff.Removed | Export-Csv (Join-Path $csvDir "diff_autoruns_removed.csv") -NoTypeInformation
  }
}

# Compare Network Connections
Write-Host "  [+] Comparing network connections..." -ForegroundColor Gray
$connDiff = Compare-CsvData `
  -BaselineCsv (Join-Path $baselineDir "csv\established_connections_with_processes.csv") `
  -CurrentCsv (Join-Path $currentDir "csv\established_connections_with_processes.csv") `
  -KeyProperties @("RemoteAddress", "RemotePort", "ProcessName")

if ($connDiff) {
  $diffReport.EstablishedConnections = [pscustomobject]@{
    Added = $connDiff.Added.Count
    Removed = $connDiff.Removed.Count
    BaselineTotal = $connDiff.BaselineCount
    CurrentTotal = $connDiff.CurrentCount
  }

  if ($connDiff.Added.Count -gt 0) {
    $connDiff.Added | Export-Csv (Join-Path $csvDir "diff_connections_added.csv") -NoTypeInformation

    foreach ($conn in $connDiff.Added) {
      $suspicion = Get-SuspicionLevel -Category "NetworkConnection" -Item $conn
      if ($suspicion -in @("High", "Medium")) {
        $diffReport.SuspiciousChanges += [pscustomobject]@{
          Category = "NetworkConnection"
          Change = "Added"
          Item = "$($conn.ProcessName) → $($conn.RemoteAddress):$($conn.RemotePort)"
          Details = "LocalPort: $($conn.LocalPort)"
          SuspicionLevel = $suspicion
        }
      }
    }
  }

  if ($connDiff.Removed.Count -gt 0) {
    $connDiff.Removed | Export-Csv (Join-Path $csvDir "diff_connections_removed.csv") -NoTypeInformation
  }
}

# Compare Patches
Write-Host "  [+] Comparing installed patches..." -ForegroundColor Gray
$patchDiff = Compare-CsvData `
  -BaselineCsv (Join-Path $baselineDir "csv\patches_hotfix.csv") `
  -CurrentCsv (Join-Path $currentDir "csv\patches_hotfix.csv") `
  -KeyProperties @("HotFixID")

if ($patchDiff) {
  $diffReport.Patches = [pscustomobject]@{
    Added = $patchDiff.Added.Count
    Removed = $patchDiff.Removed.Count
    BaselineTotal = $patchDiff.BaselineCount
    CurrentTotal = $patchDiff.CurrentCount
  }

  if ($patchDiff.Added.Count -gt 0) {
    $patchDiff.Added | Export-Csv (Join-Path $csvDir "diff_patches_added.csv") -NoTypeInformation
  }

  if ($patchDiff.Removed.Count -gt 0) {
    $patchDiff.Removed | Export-Csv (Join-Path $csvDir "diff_patches_removed.csv") -NoTypeInformation
  }
}

# Compare Shares
Write-Host "  [+] Comparing network shares..." -ForegroundColor Gray
$shareDiff = Compare-CsvData `
  -BaselineCsv (Join-Path $baselineDir "csv\shares.csv") `
  -CurrentCsv (Join-Path $currentDir "csv\shares.csv") `
  -KeyProperties @("Name", "Path")

if ($shareDiff) {
  $diffReport.Shares = [pscustomobject]@{
    Added = $shareDiff.Added.Count
    Removed = $shareDiff.Removed.Count
    BaselineTotal = $shareDiff.BaselineCount
    CurrentTotal = $shareDiff.CurrentCount
  }

  if ($shareDiff.Added.Count -gt 0) {
    $shareDiff.Added | Export-Csv (Join-Path $csvDir "diff_shares_added.csv") -NoTypeInformation

    foreach ($share in $shareDiff.Added) {
      $diffReport.SuspiciousChanges += [pscustomobject]@{
        Category = "Share"
        Change = "Added"
        Item = "$($share.Name) → $($share.Path)"
        Details = "Description: $($share.Description)"
        SuspicionLevel = "Medium"
      }
    }
  }

  if ($shareDiff.Removed.Count -gt 0) {
    $shareDiff.Removed | Export-Csv (Join-Path $csvDir "diff_shares_removed.csv") -NoTypeInformation
  }
}

# Export suspicious changes
if ($diffReport.SuspiciousChanges.Count -gt 0) {
  $diffReport.SuspiciousChanges | Sort-Object SuspicionLevel -Descending |
    Export-Csv (Join-Path $csvDir "suspicious_changes_summary.csv") -NoTypeInformation
}

# Save JSON report
$jsonPath = Join-Path $diffDir "diff_report.json"
($diffReport | ConvertTo-Json -Depth 10) | Out-File $jsonPath -Encoding UTF8 -Force

# Create HTML report
$htmlPath = Join-Path $diffDir "diff_report.html"

$htmlStyle = @"
<style>
  body { font-family: 'Segoe UI', sans-serif; margin: 20px; background: #f5f5f5; }
  .header { background: linear-gradient(135deg, #e74c3c 0%, #c0392b 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 20px; }
  .header h1 { margin: 0; }
  .section { background: white; padding: 20px; margin-bottom: 20px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
  .section h2 { color: #e74c3c; border-bottom: 2px solid #e74c3c; padding-bottom: 10px; }
  table { border-collapse: collapse; width: 100%; }
  th { background: #e74c3c; color: white; padding: 12px; text-align: left; }
  td { padding: 10px; border-bottom: 1px solid #e0e0e0; }
  tr:hover { background: #f8f9fa; }
  .metric { display: inline-block; background: #f8f9fa; padding: 15px 20px; margin: 10px 10px 10px 0; border-radius: 8px; }
  .metric-label { font-size: 0.85em; color: #666; text-transform: uppercase; }
  .metric-value { font-size: 1.5em; font-weight: bold; color: #333; }
  .added { border-left: 4px solid #27ae60; }
  .removed { border-left: 4px solid #95a5a6; }
  .suspicious-high { background: #f8d7da; border-left: 4px solid #dc3545; }
  .suspicious-medium { background: #fff3cd; border-left: 4px solid #ffc107; }
  .suspicious-low { background: #d1ecf1; border-left: 4px solid #17a2b8; }
  a { color: #e74c3c; }
</style>
"@

$suspiciousSection = ""
if ($diffReport.SuspiciousChanges.Count -gt 0) {
  $highCount = ($diffReport.SuspiciousChanges | Where-Object SuspicionLevel -eq "High").Count
  $mediumCount = ($diffReport.SuspiciousChanges | Where-Object SuspicionLevel -eq "Medium").Count

  $suspiciousHtml = $diffReport.SuspiciousChanges |
    Sort-Object SuspicionLevel -Descending |
    ConvertTo-Html -Property Category, Change, Item, Details, SuspicionLevel -Fragment

  $suspiciousSection = @"
<div class="section suspicious-high">
  <h2>⚠️ SUSPICIOUS CHANGES DETECTED</h2>
  <div style="font-size: 1.2em; margin-bottom: 15px;">
    <strong>High Risk: $highCount</strong> | <strong>Medium Risk: $mediumCount</strong>
  </div>
  $suspiciousHtml
  <div style="margin-top: 15px; padding: 10px; background: rgba(255,255,255,0.3); border-radius: 5px;">
    <strong>Action Required:</strong> Investigate all High and Medium risk changes immediately.
    Review CSV files for detailed information.
  </div>
</div>
"@
}

$summaryMetrics = @"
<div class="metric added">
  <div class="metric-label">Processes Added</div>
  <div class="metric-value">$(if ($diffReport.Processes) { $diffReport.Processes.Added } else { 'N/A' })</div>
</div>
<div class="metric added">
  <div class="metric-label">Services Added</div>
  <div class="metric-value">$(if ($diffReport.Services) { $diffReport.Services.Added } else { 'N/A' })</div>
</div>
<div class="metric added">
  <div class="metric-label">Tasks Added</div>
  <div class="metric-value">$(if ($diffReport.ScheduledTasks) { $diffReport.ScheduledTasks.Added } else { 'N/A' })</div>
</div>
<div class="metric added">
  <div class="metric-label">Users Added</div>
  <div class="metric-value">$(if ($diffReport.Users) { $diffReport.Users.Added } else { 'N/A' })</div>
</div>
<div class="metric added">
  <div class="metric-label">Admins Added</div>
  <div class="metric-value">$(if ($diffReport.GroupMembers) { ($diffReport.GroupMembers.Added) } else { 'N/A' })</div>
</div>
<div class="metric added">
  <div class="metric-label">Autoruns Added</div>
  <div class="metric-value">$(if ($diffReport.Autoruns) { $diffReport.Autoruns.Added } else { 'N/A' })</div>
</div>
"@

$summaryTable = @()
foreach ($key in $diffReport.Keys) {
  if ($key -notin @('Metadata', 'SuspiciousChanges') -and $diffReport[$key]) {
    $summaryTable += [pscustomobject]@{
      Category = $key
      Added = $diffReport[$key].Added
      Removed = $diffReport[$key].Removed
      BaselineTotal = $diffReport[$key].BaselineTotal
      CurrentTotal = $diffReport[$key].CurrentTotal
    }
  }
}

$summaryHtml = $summaryTable | ConvertTo-Html -Property Category, Added, Removed, BaselineTotal, CurrentTotal -Fragment

$htmlContent = @"
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Inventory Diff Report - CCDC</title>
  $htmlStyle
</head>
<body>
  <div class="header">
    <h1>📊 Windows Inventory Diff Report</h1>
    <p><b>Baseline:</b> $($diffReport.Metadata.BaselineName)</p>
    <p><b>Current:</b> $($diffReport.Metadata.CurrentName)</p>
    <p><b>Compared:</b> $($diffReport.Metadata.ComparisonTime)</p>
  </div>

  $suspiciousSection

  <div class="section">
    <h2>📈 Change Summary</h2>
    $summaryMetrics
  </div>

  <div class="section">
    <h2>📋 Detailed Comparison</h2>
    $summaryHtml
  </div>

  <div class="section">
    <h2>📁 Detailed CSV Files</h2>
    <p>Review CSV files in the <b>csv/</b> folder for complete details:</p>
    <ul>
      <li><a href="csv/suspicious_changes_summary.csv">suspicious_changes_summary.csv</a> - All suspicious changes</li>
      <li><a href="csv/diff_processes_added.csv">diff_processes_added.csv</a> - New processes</li>
      <li><a href="csv/diff_services_added.csv">diff_services_added.csv</a> - New services</li>
      <li><a href="csv/diff_scheduled_tasks_added.csv">diff_scheduled_tasks_added.csv</a> - New tasks</li>
      <li><a href="csv/diff_users_added.csv">diff_users_added.csv</a> - New users</li>
      <li><a href="csv/diff_group_members_added.csv">diff_group_members_added.csv</a> - New group members</li>
      <li><a href="csv/diff_autoruns_added.csv">diff_autoruns_added.csv</a> - New autoruns</li>
      <li><a href="csv/diff_connections_added.csv">diff_connections_added.csv</a> - New connections</li>
    </ul>
  </div>

  <div style="text-align: center; padding: 20px; color: #666;">
    <p>Generated by Compare-WindowsInventory.ps1 (CCDC Edition)</p>
  </div>
</body>
</html>
"@

$htmlContent | Out-File $htmlPath -Encoding UTF8 -Force

# Console summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  Comparison Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""

Write-Host "Diff Report: " -NoNewline
Write-Host $diffDir -ForegroundColor Cyan
Write-Host "HTML Report: " -NoNewline
Write-Host $htmlPath -ForegroundColor Cyan
Write-Host ""

if ($diffReport.SuspiciousChanges.Count -gt 0) {
  Write-Host "⚠️  SUSPICIOUS CHANGES DETECTED" -ForegroundColor Red
  Write-Host ""

  $high = ($diffReport.SuspiciousChanges | Where-Object SuspicionLevel -eq "High").Count
  $medium = ($diffReport.SuspiciousChanges | Where-Object SuspicionLevel -eq "Medium").Count

  Write-Host "  High Risk:   $high" -ForegroundColor Red
  Write-Host "  Medium Risk: $medium" -ForegroundColor Yellow
  Write-Host ""

  Write-Host "  Review: csv/suspicious_changes_summary.csv" -ForegroundColor Yellow
  Write-Host ""
} else {
  Write-Host "✓ No highly suspicious changes detected" -ForegroundColor Green
  Write-Host ""
}

Write-Host "Change Summary:" -ForegroundColor Cyan
if ($diffReport.Processes) {
  Write-Host "  Processes:        +$($diffReport.Processes.Added) / -$($diffReport.Processes.Removed)" -ForegroundColor Gray
}
if ($diffReport.Services) {
  Write-Host "  Services:         +$($diffReport.Services.Added) / -$($diffReport.Services.Removed)" -ForegroundColor Gray
}
if ($diffReport.ScheduledTasks) {
  Write-Host "  Scheduled Tasks:  +$($diffReport.ScheduledTasks.Added) / -$($diffReport.ScheduledTasks.Removed)" -ForegroundColor Gray
}
if ($diffReport.Users) {
  Write-Host "  Users:            +$($diffReport.Users.Added) / -$($diffReport.Users.Removed)" -ForegroundColor Gray
}
if ($diffReport.GroupMembers) {
  Write-Host "  Group Members:    +$($diffReport.GroupMembers.Added) / -$($diffReport.GroupMembers.Removed)" -ForegroundColor Gray
}
if ($diffReport.Software) {
  Write-Host "  Software:         +$($diffReport.Software.Added) / -$($diffReport.Software.Removed)" -ForegroundColor Gray
}
if ($diffReport.Autoruns) {
  Write-Host "  Autoruns:         +$($diffReport.Autoruns.Added) / -$($diffReport.Autoruns.Removed)" -ForegroundColor Gray
}
if ($diffReport.EstablishedConnections) {
  Write-Host "  Connections:      +$($diffReport.EstablishedConnections.Added) / -$($diffReport.EstablishedConnections.Removed)" -ForegroundColor Gray
}

Write-Host ""
